# Generated by Django 4.2.6 on 2024-01-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attritiondata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField(default=0)),
                ('BusinessTravel', models.CharField(choices=[('Travel_Rarely', 'Travel_Rarely'), ('Travel_Frequently', 'Travel_Frequently'), ('Non-Travel', 'Non-Travel')], max_length=100)),
                ('DailyRate', models.IntegerField(default=0)),
                ('Department', models.CharField(choices=[('Sales', 'Sales'), ('Research_&_Development', 'Research_&_Development'), ('Human_Resources', 'Human_Resources')], max_length=100)),
                ('DistanceFromHome', models.IntegerField(default=0)),
                ('Education', models.IntegerField(default=0)),
                ('EducationField', models.CharField(choices=[('Life_Sciences', 'Life_Sciences'), ('Medical', 'Medical'), ('other', 'other'), ('Marketing', 'Marketing'), ('Technical_Degree', 'Technical_Degree'), ('Human_Resources', 'Human_Resources')], max_length=100)),
                ('EmployeeNumber', models.IntegerField(default=0)),
                ('EnvironmentSatisfaction', models.IntegerField(default=0)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('HourlyRate', models.IntegerField(default=0)),
                ('JobInvolvement', models.IntegerField(default=0)),
                ('JobLevel', models.IntegerField(default=0)),
                ('JobRole', models.CharField(choices=[('Sales_Executive', 'Sales_Executive'), ('Research_Scientist', 'Research_Scientist'), ('Laboratory_Technician', 'Laboratory_Technician'), ('Manufacturing_Director', 'Manufacturing_Director'), ('Research_Director', 'Research_Director'), ('Healthcare_Representative', 'Healthcare_Representative'), ('manager', 'Manager'), ('Sales_Representative', 'Sales_Representative')], max_length=100)),
                ('JobSatisfaction', models.IntegerField(default=0)),
                ('MaritalStatus', models.CharField(choices=[('Married', 'Married'), ('single', 'Single'), ('Divorced', 'Divorced')], max_length=100)),
                ('MonthlyIncome', models.IntegerField(default=0)),
                ('MonthlyRate', models.IntegerField(default=0)),
                ('NumCompaniesWorked', models.IntegerField(default=0)),
                ('OverTime', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100)),
                ('PercentSalaryHike', models.IntegerField(default=0)),
                ('PerformanceRating', models.IntegerField(default=0)),
                ('RelationshipSatisfaction', models.IntegerField(default=0)),
                ('StockOptionLevel', models.IntegerField(default=0)),
                ('TotalWorkingYears', models.IntegerField(default=0)),
                ('TrainingTimesLastYear', models.IntegerField(default=0)),
                ('WorkLifeBalance', models.IntegerField(default=0)),
                ('YearsAtCompany', models.IntegerField(default=0)),
                ('YearsInCurrentRole', models.IntegerField(default=0)),
                ('YearsSinceLastPromotion', models.IntegerField(default=0)),
                ('YearsWithCurrManager', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'myapi_attritiondata',
            },
        ),
    ]
